---
- name: Configure aggregator
  hosts: aggregator
  vars:
    vector_user_configs_paths:
      - "{{ playbook_dir }}/../files/aggregator"
    clickhouse_local_endpoint: "{{ hostvars[inventory_hostname].clickhouse_local_endpoint }}"
    vector_kafka_sasl_password: "{{ lookup('ansible.builtin.env', 'VECTOR_KAFKA_PASSWORD') }}"
    vector_kafka_sasl_username: "{{ lookup('ansible.builtin.env', 'VECTOR_KAFKA_USERNAME') }}"
  vars_files:
    - "{{ playbook_dir }}/vars/metrics-catalog.{{ vector_environment }}.yml"
  ignore_errors: true
  tasks:
    - name: "Local Build. Generate Vector Config Files"
      ansible.builtin.include_tasks: tasks/vector_config_generate_tasks.yml
      when: local_build | default(False)

  tags:
    - aggregator
